CadeMeuMedico/Controllers/MedicoController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using CadeMeuMedico.Models;

namespace CadeMeuMedico.Controllers
{
    public class MedicoController : Controller
    {
        //
        // GET: /Medicos/
        private readonly EntidadesCadeMeuMedicoBD db = new EntidadesCadeMeuMedicoBD();

        public ActionResult Index()
        {
            List<Medico> medicos = db.Medicos.Include(m => m.Cidade).Include(m => m.Especialidade).ToList();
            return View(medicos);
        }

        public ActionResult Adicionar()
        {
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades,
                "IDEspecialidade",
                "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Medico medico)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade",
                "Nome",
                medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades,
                "IDEspecialidade",
                "Nome",
                medico.IDEspecialidade);
            return View(medico);
        }

        public ActionResult Editar(long id)
        {
            Medico medico = db.Medicos.Find(id);
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade",
                "Nome",
                medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades,
                "IDEspecialidade",
                "Nome",
                medico.IDEspecialidade);
            return View(medico);
        }

        [HttpPost]
        public ActionResult Editar(Medico medico)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade",
                "Nome",
                medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades,
                "IDEspecialidade",
                "Nome",
                medico.IDEspecialidade);
            return View(medico);
        }
    }
}

CadeMeuMedico/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cade meu medico? - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")"
          rel="stylesheet" />
    <style>
        body {
            padding-top: 60px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Cade meu medico?</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Médicos", "Index", "Medico")
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>

    <script src="@Url.Content("~/Scripts/jquery-2.1.1.min.js")">
    </script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")">
    </script>
    @RenderSection("script", required: false);

</body>
</html>